import type { ModelInfo } from "../model.js"

// Ford LLM models available through Ford's internal API
export type FordLlmModelId = keyof typeof fordllmModels

export const fordllmDefaultModelId: FordLlmModelId = "fordllm-coding-model"

export const fordllmModels = {
	// Recommended Ford LLM Aliases (use these for best experience)
	"fordllm-coding-model": {
		maxTokens: 16_384,
		contextWindow: 128_000,
		supportsImages: true,
		supportsPromptCache: true,
		supportsTemperature: true,
		defaultTemperature: 1,
		inputPrice: 0, // On-prem (Deepseek V3.1)
		outputPrice: 0,
		description: "Optimized for coding tasks (Deepseek V3.1, on-prem)",
	},
	"fordllm-reasoning-model": {
		maxTokens: 65_536,
		contextWindow: 1_048_576,
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningEffort: ["low", "high"],
		reasoningEffort: "low",
		supportsTemperature: true,
		defaultTemperature: 1,
		inputPrice: 1.25, // GPT-5
		outputPrice: 10,
		description: "Best for complex reasoning tasks (GPT-5)",
	},
	"fordllm-openai-flagship-model": {
		maxTokens: 65_536,
		contextWindow: 1_048_576,
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningEffort: ["low", "high"],
		reasoningEffort: "low",
		supportsTemperature: true,
		defaultTemperature: 1,
		inputPrice: 1.25, // GPT-5
		outputPrice: 10,
		description: "OpenAI flagship model (GPT-5)",
	},
	"fordllm-openai-mini-model": {
		maxTokens: 16_384,
		contextWindow: 128_000,
		supportsImages: true,
		supportsPromptCache: true,
		supportsTemperature: true,
		defaultTemperature: 1,
		inputPrice: 0.25, // GPT-5 mini
		outputPrice: 2,
		description: "Fast general-purpose model (GPT-5 mini)",
	},
	"fordllm-openai-fast-model": {
		maxTokens: 16_384,
		contextWindow: 128_000,
		supportsImages: true,
		supportsPromptCache: true,
		supportsTemperature: true,
		defaultTemperature: 1,
		inputPrice: 0.05, // GPT-5 nano
		outputPrice: 0.4,
		description: "Fastest and most cost-effective model (GPT-5 nano)",
	},
	"fordllm-claude-latest": {
		maxTokens: 8192,
		contextWindow: 200_000,
		supportsImages: true,
		supportsPromptCache: true,
		supportsTemperature: true,
		defaultTemperature: 1,
		inputPrice: 3, // Claude Sonnet 4.5
		outputPrice: 15,
		description: "Latest Claude model (Sonnet 4.5)",
	},

	// Gemini Models
	"gemini-2.5-pro": {
		maxTokens: 65_536,
		contextWindow: 1_048_576,
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningEffort: ["low", "high"],
		reasoningEffort: "low",
		supportsTemperature: true,
		defaultTemperature: 1,
		inputPrice: 1.25,
		outputPrice: 10,
		description: "Multimodal LLM for complex problems",
	},
	"gemini-2.5-flash": {
		maxTokens: 8192,
		contextWindow: 1_048_576,
		supportsImages: true,
		supportsPromptCache: true,
		supportsTemperature: true,
		defaultTemperature: 1,
		inputPrice: 0.3,
		outputPrice: 2.5,
		description: "Balances cost and performance",
	},
	"gemini-2.5-flash-lite": {
		maxTokens: 8192,
		contextWindow: 1_048_576,
		supportsImages: true,
		supportsPromptCache: true,
		supportsTemperature: true,
		defaultTemperature: 1,
		inputPrice: 0.1,
		outputPrice: 0.4,
		description: "Smallest and most cost-effective Gemini model",
	},
	"gemini-2.0-flash-exp": {
		maxTokens: 8192,
		contextWindow: 1_048_576,
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningEffort: ["low", "high"],
		reasoningEffort: "low",
		supportsTemperature: true,
		defaultTemperature: 1,
		inputPrice: 0,
		outputPrice: 0,
		description: "Experimental Gemini 2.0 Flash",
	},
	"gemini-2.0-flash-001": {
		maxTokens: 8192,
		contextWindow: 1_048_576,
		supportsImages: true,
		supportsPromptCache: true,
		supportsTemperature: true,
		defaultTemperature: 1,
		inputPrice: 0,
		outputPrice: 0,
	},
	"gemini-1.5-pro": {
		maxTokens: 8192,
		contextWindow: 2_097_152,
		supportsImages: true,
		supportsPromptCache: true,
		supportsTemperature: true,
		defaultTemperature: 1,
		inputPrice: 0,
		outputPrice: 0,
	},
	"gemini-1.5-flash": {
		maxTokens: 8192,
		contextWindow: 1_048_576,
		supportsImages: true,
		supportsPromptCache: true,
		supportsTemperature: true,
		defaultTemperature: 1,
		inputPrice: 0,
		outputPrice: 0,
	},

	// GPT Models
	"gpt-5-2025-08-07": {
		maxTokens: 16_384,
		contextWindow: 128_000,
		supportsImages: true,
		supportsPromptCache: true,
		supportsTemperature: true,
		defaultTemperature: 1,
		inputPrice: 1.25,
		outputPrice: 10,
		description: "Excels at coding and agentic tasks",
	},
	"gpt-5-mini-2025-08-07": {
		maxTokens: 16_384,
		contextWindow: 128_000,
		supportsImages: true,
		supportsPromptCache: true,
		supportsTemperature: true,
		defaultTemperature: 1,
		inputPrice: 0.25,
		outputPrice: 2,
		description: "Faster, more cost-efficient version of GPT-5",
	},
	"gpt-5-nano-2025-08-07": {
		maxTokens: 16_384,
		contextWindow: 128_000,
		supportsImages: true,
		supportsPromptCache: true,
		supportsTemperature: true,
		defaultTemperature: 1,
		inputPrice: 0.05,
		outputPrice: 0.4,
		description: "Fastest and most cost-effective GPT-5 variant",
	},
	"gpt-4.1-2025-04-14": {
		maxTokens: 16_384,
		contextWindow: 128_000,
		supportsImages: true,
		supportsPromptCache: true,
		supportsTemperature: true,
		defaultTemperature: 1,
		inputPrice: 2,
		outputPrice: 8,
		description: "Excels at function calling and instruction following",
	},
	"gpt-4.1-mini-2025-04-14": {
		maxTokens: 16_384,
		contextWindow: 128_000,
		supportsImages: true,
		supportsPromptCache: true,
		supportsTemperature: true,
		defaultTemperature: 1,
		inputPrice: 0.4,
		outputPrice: 1.6,
		description: "Balance between intelligence, speed, and cost",
	},
	"o4-mini-2025-04-16": {
		maxTokens: 100_000,
		contextWindow: 128_000,
		supportsImages: true,
		supportsPromptCache: true,
		supportsReasoningEffort: ["low", "medium", "high"],
		reasoningEffort: "medium",
		supportsTemperature: true,
		defaultTemperature: 1,
		inputPrice: 1.1,
		outputPrice: 4.4,
		description: "Optimized for fast, effective reasoning",
	},

	// Claude Models
	"claude-sonnet-4-5": {
		maxTokens: 8192,
		contextWindow: 200_000,
		supportsImages: true,
		supportsPromptCache: true,
		supportsTemperature: true,
		defaultTemperature: 1,
		inputPrice: 3,
		outputPrice: 15,
		description: "Hybrid reasoning model with superior intelligence for agents",
	},
	"claude-sonnet-4": {
		maxTokens: 8192,
		contextWindow: 200_000,
		supportsImages: true,
		supportsPromptCache: true,
		supportsTemperature: true,
		defaultTemperature: 1,
		inputPrice: 3,
		outputPrice: 15,
		description: "Superior intelligence for high-volume use cases",
	},
	"claude-3.7-sonnet": {
		maxTokens: 8192,
		contextWindow: 200_000,
		supportsImages: true,
		supportsPromptCache: true,
		supportsTemperature: true,
		defaultTemperature: 1,
		inputPrice: 3,
		outputPrice: 15,
		description: "Excels in large-scale coding and complex reasoning",
	},
	"claude-3.5-sonnet": {
		maxTokens: 8192,
		contextWindow: 200_000,
		supportsImages: true,
		supportsPromptCache: true,
		supportsTemperature: true,
		defaultTemperature: 1,
		inputPrice: 3,
		outputPrice: 15,
		description: "Excels in coding, writing, and natural conversation",
	},
} satisfies Record<string, ModelInfo>
